apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: container
  template:
    metadata:
      labels:
        app: container
    spec:
      containers:
      - name: container
        image: ash0semlali/container:latest
        ports:
        - containerPort: 8005

---
apiVersion: v1
kind: Service
metadata:
  name: container-service
spec:
  selector:
    app: container
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8005
  type: NodePort
