# auth-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: your-docker-repository/auth:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

# marketing-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketing-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: marketing
  template:
    metadata:
      labels:
        app: marketing
    spec:
      containers:
      - name: marketing
        image: your-docker-repository/marketing:latest
        ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: marketing-service
spec:
  selector:
    app: marketing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081

# dashboard-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dashboard
  template:
    metadata:
      labels:
        app: dashboard
    spec:
      containers:
      - name: dashboard
        image: your-docker-repository/dashboard:latest
        ports:
        - containerPort: 8083

---
apiVersion: v1
kind: Service
metadata:
  name: dashboard-service
spec:
  selector:
    app: dashboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083

# container-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: container
  template:
    metadata:
      labels:
        app: container
    spec:
      containers:
      - name: container
        image: your-docker-repository/container:latest
        ports:
        - containerPort: 8005

---
apiVersion: v1
kind: Service
metadata:
  name: container-service
spec:
  selector:
    app: container
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8005
  type: NodePort
