---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: marketing
  template:
    metadata:
      labels:
        app: marketing
    spec:
      containers:
      - name: marketing
        image: ash0semlali/marketing
        ports:
        - containerPort: 8081

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: ash0semlali/auth
      ports:
        - containerPort: 8082

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard
  template:
    metadata:
      labels:
        app: dashboard
    spec:
      containers:
        - name: dashboard
          image: ash0semlali/dashboard
      ports:
        - containerPort: 8083
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container
  template:
    metadata:
      labels:
        app: container
    spec:
      containers:
        - name: container
          image: ash0semlali/container
      ports:
        - containerPort: 8088

---

apiVersion: v1
kind: Service
metadata:
  name: container
spec:
  selector:
    app: container
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
  type: LoadBalancer
