---
- name: Configure Kubernetes Cluster
  hosts: kubernetes_nodes
  become: true
  vars:
    kube_version: "1.18.1-00"  
   
  tasks:
    - name: Update package repository
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install apt-transport-https and curl
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - curl

    - name: Add Kubernetes key and repo
      command: "curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add - && echo 'deb https://apt.kubernetes.io/ kubernetes-xenial main' | sudo tee /etc/apt/sources.list.d/kubernetes.list"
    
    - name: Update package repository and Install K8S components
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - kubelet={{ kube_version }}
        - kubeadm={{ kube_version }}
        - kubectl={{ kube_version }}
      notify: restart kubelet

    - name: Add hosts entry
      lineinfile:
        path: /etc/hosts
        line: "{{ ansible_default_ipv4.address }} kube-master"

    - name: Disable SWAP
      command: "sudo swapoff -a"
      notify: remove swap entry

    - name: Initiate the Cluster on Master node
      command: "sudo kubeadm init --control-plane-endpoint kube-master:6443 --pod-network-cidr {{ pod_network_cidr }}"
      when: "'kubernetes_master' in group_names"
      notify: set kubectl context auth

    - name: Set kubectl context auth on Master node
      command: "mkdir -p $HOME/.kube && sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config && sudo chown $(id -u):$(id -g) $HOME/.kube/config"
      when: "'kubernetes_master' in group_names"

    - name: Pod Network Addon (Calico) on Master node
      command: "curl https://docs.projectcalico.org/manifests/calico.yaml -O && vi calico.yaml"
      when: "'kubernetes_master' in group_names"

    - name: Generate Token on Master node
      command: "sudo kubeadm token create"
      when: "'kubernetes_master' in group_names"
      register: token_output

    - name: List Tokens on Master node
      command: "sudo kubeadm token list"
      when: "'kubernetes_master' in group_names"

    - name: Find Certificate Hash on Master node
      command: "openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //' "
      when: "'kubernetes_master' in group_names"
      register: cert_hash_output

    - name: Join Nodes on Worker nodes
      command: "sudo kubeadm join --token {{ token_output.stdout }} kube-master:6443 --discovery-token-ca-cert-hash sha256:{{ cert_hash_output.stdout }}"
      when: "'kubernetes_workers' in group_names"

    - name: Taint Master Node
      command: "kubectl taint nodes -all node-role.kubernetes.io/master"
      when: "'kubernetes_master' in group_names"

  handlers:
    - name: restart kubelet
      systemd:
        name: kubelet
        state: restarted

    - name: remove swap entry
      lineinfile:
        path: /etc/fstab
        state: absent
        regexp: '^/swap.img'
