apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-service-1
  template:
    metadata:
      labels:
        app: frontend-service-1
    spec:
      containers:
      - name: frontend-container-1
        image: your-registry/frontend-service-1:latest
        ports:
        - containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-service-2
  template:
    metadata:
      labels:
        app: frontend-service-2
    spec:
      containers:
      - name: frontend-container-2
        image: your-registry/frontend-service-2:latest
        ports:
        - containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service-3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-service-3
  template:
    metadata:
      labels:
        app: frontend-service-3
    spec:
      containers:
      - name: frontend-container-3
        image: your-registry/frontend-service-3:latest
        ports:
        - containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service-4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-service-4
  template:
    metadata:
      labels:
        app: frontend-service-4
    spec:
      containers:
      - name: frontend-container-4
        image: your-registry/frontend-service-4:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-load-balancer
spec:
  selector:
    app: frontend-service-1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

