apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketing-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marketing
  template:
    metadata:
      labels:
        app: marketing
    spec:
      containers:
      - name: marketing
        image: ash0semlali/marketing:latest
        ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: marketing-service
spec:
  selector:
    app: marketing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
